### ISSUE TITLE
Testing addon and Source Code?

### ISSUE THREAD

**Issue by daleathan** [sam-m888/TMGimporter#1]
Hi @sam-m888 

Had you intended to publish the code for the addon?

If required I'd be interested in testing this addon further, if you recall I have still have the previous version you sent me.

Dale

**Comment by sam-m888** [comment]
> Had you intended to publish the code for the addon?

Yes, but only when I felt it was finished, If I have time this weekend I will just commit a stripped down version (no importing), as due to the changes made to Gramps master in the last 3 months the addon no longer works and needs to be updated because certain Gramps methods have been replaced!

You maybe interested in the new repo for [HRE-the-history-of-everything](https://github.com/HREferg/HRE-the-history-of-everything) which will eventually import TMG files also.

**Comment by sam-m888** [comment]
My progress has stalled due to lack of time, will look again in November. 

In the meantime have added what I have so far to the gramps addons-source repository, that processes the SQZ file right up to the point that it is ready for the tables to be imported into Gramps eg the hard bit!

* TMGImporter  on gramps addons-source repository
https://github.com/gramps-project/addons-source/tree/master/TMGimporter

* Wiki Help page
https://gramps-project.org/wiki/index.php?title=Addon:TMGimporter

* Related Gramps Feature request
https://gramps-project.org/bugs/view.php?id=7591


This repository will be used for support files related to the creation of the addon.
